# Generated by Django 4.1.1 on 2023-03-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='product', verbose_name='Image')),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('Date_uz', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('Date_en', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('Date_ru', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='Image',
        ),
        migrations.AddField(
            model_name='product',
            name='Images',
            field=models.ManyToManyField(to='importapp.product_image'),
        ),
    ]
