# Generated by Django 4.1.1 on 2023-04-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importapp', '0005_remove_product_image_date_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiToken', models.CharField(max_length=255, verbose_name='Api Token')),
                ('chatID', models.CharField(max_length=255, verbose_name='Chat Id')),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Telegram',
                'verbose_name_plural': 'G - Telegram',
            },
        ),
    ]
